### ISSUE TITLE
Please add source distrubution files on PyPI

### ISSUE THREAD

**Issue by rombert** [pmuller/saltstack-age-renderer#28]
Hi,

I am trying to package this project as an RPM using the Open Build Service. The canonical openSUSE workflow for Python packages is to use `py2pack`, which requires source releases.

```
$ py2pack fetch saltstack-age
unable to find a source release for saltstack-age!
```

Can you please upload source releases to PyPI?

Thanks!

**Comment by pmuller** [comment]
Done: https://pypi.org/project/saltstack-age/0.4.0/#files
All future releases will have both wheel and source packages.

**Comment by rombert** [comment]
Thanks a lot for the quick fix @pmuller ! I started but it's going to take some time - pyrage has a more involved building process where they require Cargo + Rust, not sure how easy that is going to be to manage.
